# Generated by Django 4.0.2 on 2022-02-27 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mo', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='gh',
        ),
    ]
