# Generated by Django 4.0.2 on 2022-03-03 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Field', models.CharField(choices=[('I', 'IT'), ('N', 'NON IT')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='HR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HR_Name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ratings', models.CharField(choices=[('1', 'one'), ('2', 'two'), ('3', 'three'), ('4', 'four'), ('5', 'five')], max_length=1)),
                ('Enter_Your_Feedback', models.CharField(max_length=30)),
                ('company_namee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_authorization.company')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_authorization.user')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='HR',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_authorization.hr'),
        ),
        migrations.AddField(
            model_name='company',
            name='categories',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_authorization.category'),
        ),
        migrations.AddField(
            model_name='company',
            name='skills',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_authorization.skill'),
        ),
    ]
