# Generated by Django 4.0.2 on 2022-02-25 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('us', '0002_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_num', models.CharField(max_length=5)),
                ('user_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='us.biodata')),
            ],
        ),
    ]
